#!/bin/sh
##########
#
#   メモ
#   引数は3つ 
#   dat → 必須
#   pak名 → オプション
#
#######
#
#   注意事項
#   事前にmakeobjをパスが通っている場所に配置するか、配置した場所のパスを通す事
#
##########

#makeobj判定

#pak化
if $# -eq 3  ; then #固めてpak化
    makeobj_55 pak $1 $2
else #バラでpak化
    makeobj_55 pak ./ $1
fi




echo "--------------------\n"

#pakの移動
for pak in *.pak
do
    cp "$pak" ~/simutrans/bin/pak.dev/
done

#検証用セットでの起動
~/simutrans/bin/simutrans_V112-3 -nomidi -nosound -freeplay -objects pak.dev/ -load DevTestMap.sve | echo > /dev/null
